### ISSUE TITLE
Remove unused importlib-metadata dependency

### ISSUE THREAD

**Issue by eleanorRumsey** [TkTech/celery-heimdall#11]
Hey! We're using this package here at Fellow, but there's a dependency conflict in `importlib-metadata` with another package (`opentelemetry-api`). It doesn't seem like `importlib-metadata` is actually used anywhere here, would it be possible to remove it?

https://github.com/TkTech/celery-heimdall/blob/b6709f636b77079e396bd704317f925f9b407381/pyproject.toml#L17

**Comment by TkTech** [comment]
Hi! This was to work around this specific issue: https://github.com/python/importlib_metadata/issues/411, which universally broke importing celery. Since this is no longer needed, the pin can be removed. I'll push 1.0.1 shortly.
